name = "Hugo Bootstrap v4 Blog"
license = "CC-BY-3.0"
licenselink = "https://github.com/joeheaton/hugo-theme-bootstrap4-blog/blob/master/LICENSE.txt"
description = "A customized version of Alan Orth's Hugo theme based on the Bootstrap v4 blog example."
homepage = "https://github.com/joeheaton/hugo-theme-bootstrap4-blog"
tags = ["bootstrap", "blog", "font awesome"]
features = ["responsive", "blog"]
min_version = 0.25

[author]
  name = "Joe Heaton"
  homepage = "https://heaton.dev"

[original]
  name = "Alan Orth"
  homepage = "https://englishbulgaria.net"

# vim: ts=2 sw=2 et
